const commands = {
    'man scp' : "scp -words [-12346BCpqrv ] [-c cipher ] [-F ssh_config ] [-i identity_file ] [-l limit ] [-o ssh_option ] [-P port ] [-S program ] \n[[user @ ] host1 : file1 ] ... [[user @ ] host2 : file2 ] \n\nscp copies files between hosts on a network. It uses ssh(1) for data transfer, and uses the same authentication and provides the \nsame security as ssh(1). scp will ask for passwords or passphrases if they are needed for authentication.\n\nFile names may contain a user and host specification to indicate that the file is to be copied to/from that host. Local file names can be made explicit using absolute or relative pathnames to avoid scp treating file names containing ':' as host specifiers. Copies between two remote hosts are also permitted.\n\nThe options are as follows:\n\n-1\n  Forces scp to use protocol 1.\n\n-2\n  Forces scp to use protocol 2.\n\n-3\n  Copies between two remote hosts are transferred through the local host. Without this option, the data is copied directly between the two remote hosts. Note that this option disables the progress meter.\n\n-4\n  Forces scp to use IPv4 addresses only.\n\n-6\n  Forces scp to use IPv6 addresses only.\n\n-B\n  Selects batch mode (prevents asking for passwords or passphrases).\n\n-C\n  Compression enabled. Passes the -C flag to ssh(1) to enable compression.\n\nc cipher\n  Selects the cipher to use for encrypting the data transfer. This option is directly passed to ssh(1).\n\n-F ssh_config\n  Specifies an alternative per-user configuration file for ssh. This option is directly passed to ssh(1).\n\n-i identity_file\n  Selects the file from which the identity (private key) for public key authentication is read. This option is directly passed to ssh(1).\n\n-l limit\n  Limits the used bandwidth, specified in Kbit/s.\n\n-o ssh_option\n  Can be used to pass options to ssh in the format used in ssh_config5. This is useful for specifying options for which there is no separate scp command-line flag. For full details of the options listed below, and their possible values, see ssh_config5.\n\n-P port\n  Specifies the port to connect to on the remote host. Note that this option is written with a capital 'P' because -p is already reserved for preserving the times and modes of the file.\n\n-p\n  Preserves modification times, access times, and modes from the original file.\n\n-q\n  Quiet mode: disables the progress meter as well as warning and diagnostic messages from ssh(1).\n\n-r\n  Recursively copy entire directories. Note that scp follows symbolic links encountered in the tree traversal.\n\n-S program\n  Name of the program to use for the encrypted connection. The program must understand ssh(1) options.\n\n-v\n  Verbose mode. Causes scp and ssh(1) to print debugging messages about their progress. This is helpful in debugging connection, authentication, and configuration problems."
    ,
    ls: 'hello.txt',
    help: "Return to your information page to review the commands you can use like:\n- scp\n- man",
  };
  
  const defaultOutput = "Command not recognized. Type 'help' for available commands.";
  
  export const handleCommand = (input) => {
    const inputLowerCase = input.trim().toLowerCase();
    return commands[inputLowerCase] || defaultOutput;
  };
  